language: node_js
node_js:
  - "7"

branches:
  only:
  - master

notifications:
  email: false

before_install:
  - chmod +x ./scripts/PRsanitycheck.py

# before_script:
#   - ./scripts/PRsanitycheck.py

script:
  - ./scripts/PRsanitycheck.py
